"""add zone_id to field_reports

Revision ID: d5510c77dac6
Revises: fd4fe80e3915
Create Date: 2026-09-04 21:10:53.257289
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd5510c77dac6'
down_revision: Union[str, None] = 'fd4fe80e3915'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('field_reports', sa.Column('zone_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'field_reports', 'risk_zones', ['zone_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'field_reports', type_='foreignkey')
    op.drop_column('field_reports', 'zone_id')
    # ### end Alembic commands ###
